version: "3.8"
services:
  database:
    image: postgres:14.8
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - database