#Change those params if needed to match your database configuration.
default: &default
  host: database
  user: test
  password: test
  adapter: postgres

development:
  <<: *default
  db: travels_api_development